jorlan {
  shell {
    serverUrl = "http://localhost:8080"
    serverUrl = ${?JORLAN_SHELL_SERVER_URL}
    email = ""
    email = ${?JORLAN_SHELL_EMAIL}
    password = ""
    password = ${?JORLAN_SHELL_PASSWORD}
  }
}
