jorlan {
  db {
    dataSource {
      driver = "org.mariadb.jdbc.Driver"
      url = ${JORLAN_DB_URL}
      user = ${JORLAN_DB_USER}
      password = ${JORLAN_DB_PASSWORD}
      maximumPoolSize = 20
      maximumPoolSize = ${?JORLAN_DB_MAX_POOL_SIZE}
      minimumIdle = 2
      connectionTimeoutMillis = 30000
    }
  }

  flyway {
    locations = ["classpath:sql"]
    enabled = true
    cleanDisabled = true
    validateOnMigrate = true
    mixed = false
    target = ""
    baselineOnMigrate = true
    baselineVersion = "0"
    baselineDescription = "Initial"
  }

  http {
    host = "0.0.0.0"
    port = 8080
    port = ${?JORLAN_HTTP_PORT}
  }
}
