jorlan {
  db {
    dataSource {
      driver = "org.mariadb.jdbc.Driver"
      url = ${JORLAN_DB_URL}
      user = ${JORLAN_DB_USER}
      password = ${JORLAN_DB_PASSWORD}
      maximumPoolSize = 20
      maximumPoolSize = ${?JORLAN_DB_MAX_POOL_SIZE}
      minimumIdle = 2
      connectionTimeoutMillis = 30000
    }
  }

  flyway {
    locations = ["classpath:sql"]
    enabled = true
    cleanDisabled = true
    validateOnMigrate = true
    mixed = false
    target = ""
    baselineOnMigrate = true
    baselineVersion = "0"
    baselineDescription = "Initial"
  }

  http {
    host = "0.0.0.0"
    port = 8080
    port = ${?JORLAN_HTTP_PORT}
  }

  auth {
    secretKey = ${JORLAN_AUTH_SECRET_KEY}
    accessTtlMinutes = 60
    accessTtlMinutes = ${?JORLAN_AUTH_ACCESS_TTL_MINUTES}
    refreshTtlDays = 30
    refreshTtlDays = ${?JORLAN_AUTH_REFRESH_TTL_DAYS}

    # google {
    #   clientId = ${JORLAN_GOOGLE_CLIENT_ID}
    #   clientSecret = ${JORLAN_GOOGLE_CLIENT_SECRET}
    #   authorizationUri = "https://accounts.google.com/o/oauth2/v2/auth"
    #   tokenUri = "https://oauth2.googleapis.com/token"
    #   userInfoUri = "https://www.googleapis.com/oauth2/v3/userinfo"
    #   redirectUri = ${JORLAN_GOOGLE_REDIRECT_URI}
    #   scopes = ["openid", "email", "profile"]
    # }
  }
}
